//APPLY_LEAVE
export const RESET_APPLY_LEAVE_STATE = "RESET_APPLY_LEAVE_STATE";
export const APPLY_LEAVE_REQUEST = "APPLY_LEAVE_REQUEST";
export const APPLY_LEAVE_SUCCESS = "APPLY_LEAVE_SUCCESS";
export const APPLY_LEAVE_FAIL = "APPLY_LEAVE_FAIL";

//GET CC DATA

export const GET_CC_REQUEST = "GET_CC_REQUEST";
export const GET_CC_SUCCESS = "GET_CC_SUCCESS";
export const GET_CC_FAIL = "GET_CC_FAIL";
