// GET ALL LEAVES TYPES
export const GET_ALL_LEAVES_REQUEST = 'GET_ALL_LEAVES_REQUEST';
export const GET_ALL_LEAVES_SUCCESS = 'GET_ALL_LEAVES_SUCCESS';
export const GET_ALL_LEAVES_FAIL = 'GET_ALL_LEAVES_FAIL';

// GET MY LEAVES TYPES
export const GET_MY_LEAVES_REQUEST = 'GET_MY_LEAVES_REQUEST';
export const GET_MY_LEAVES_SUCCESS = 'GET_MY_LEAVES_SUCCESS';
export const GET_MY_LEAVES_FAIL = 'GET_MY_LEAVES_FAIL';

//UPDATE LEAVE REQUEST
export const UPDATE_LEAVE_REQUEST = 'UPDATE_LEAVE_REQUEST';
export const UPDATE_LEAVE_SUCESS = 'UPDATE_LEAVE_SUCESS';
export const UPDATE_LEAVE_FAIL = 'UPDATE_LEAVEFAIL';

//SINGLE LEAVE DATA
export const LEAVE_DETAIL_REQUEST = 'LEAVE_DETAIL_REQUEST';
export const LEAVE_DETAIL_SUCESS = 'LEAVE_DETAIL_SUCESS';
export const LEAVE_DETAIL_FAIL = 'LEAVE_DETAIL_FAIL';
export const LEAVE_DETAIL_EMPTY = 'LEAVE_DETAIL_EMPTY';

//SHOW COMMENTS
export const SHOW_COMMENT_REQUEST = 'SHOW_COMMENT_REQUEST';
export const SHOW_COMMENT_SUCCESS = 'SHOW_COMMENT_SUCESS';
export const SHOW_COMMENT_FAIL = 'SHOW_COMMENT_FAIL';

//UPLOAD TIMESHEET
export const UPLOAD_TIMESHEET_REQUEST = 'UPLOAD_TIMESHEET_REQUEST';
export const UPLOAD_TIMESHEET_SUCCESS = 'UPLOAD_TIMESHEET_SUCCESS';
export const UPLOAD_TIMESHEET_FAIL = ' UPLOAD_TIMESHEET_FAIL';

// CURRENT TAB
export const CURRENT_TAB = 'CURRENT_TAB';
