export const Message = {
  errors: {
    EMAIL_CAN_NOT_REMOVE: "You can't remove this email",
    FIELDS_NOT_EMPTY: "Fields cann't be empty",
    USER_LOGIN_ERROR: "User unable to login",
    USER_REGISTER_ERROR: "User unable to register",
    USER_LOGOUT_ERROR: "User unable to logout",
    USER_FULLNAME: "Fullname is required",
    AADHAR_NUMBER: "Aadhar Number is required",
    ACCOUNT_NUMBER: "Account Number is required",
    UAN_NUMBER: "UAN Number is required",
    PAN_NUMBER: "PAN Number is required",
    ESI_NUMBER: "ESI Number is required",
   
    USER_EMAIL: "Email is required",
    USER_SALARY: "Salary is not empty",
    USER_VALID_EMAIL: "Email is not valid",
    USER_PASSWORD: "Password is required",
    USER_CONFIRM_PASSWORD: "Confirm password is required",
    USER_PASSWORD_CONFORMATION:
      "Password and Confirm password are not matching",
    USER_DOB: "DOB is required",
    USER_JOINING_DATE: "Joining date  is required",
    USER_LEAVES: "Leaves is required",
    USER_ROLE: "Role is required",
    COMMENT_CAN_NOT_EMPTY: "Comment can't be empty",
    OLD_UNAPPROVED_DATE: "Old Date can't be unapproved",
    USER_EMP: "Employee code is required",
    GENERATE_SALARY_PASSWORD_ERROR: "Unable to generate salary Password",
    CHANGE_PASSWORD_ERROR: "Unable to change Password",
    SOMETHING_WENT_WRONG: 'Something went wrong',
    PASSWORD_CAN_NOT_EMPTY: "Password can not be empty",
    FILE_UPLOAD_ERROR: "All field required",
    FILL_DETAILS_ERROR: "Please Fill Details correct",
  },
  info: {
    USER_EMP_CODE: 'Employee code not be greater than 4',
    USER_VALID_FULLNAME: 'Minimum 5 char required',
    USER_FULLNAME_CHAR: 'Fullname must be character only',
    USER_EMAIL_CHAR: 'Minimum 2 char required',
    USER_VALID_PASSWORD: 'Password must contain alphabet and number',
    USER_TOTAL_LEAVES: 'Total leaves must be greater than 0',
    CSV_PASSWORD: 'Minimum 6 length required',
    INVALID_AADHAR:"Invalid Aadhaar Number",
    INVALID_ACCOUNT:"Invalid Account Number",
    INVALID_UAN:"Invalid UAN Number",
    INVALID_ESI:"Invalid ESI Number",
    INVALID_PAN:"Invalid PAN Number",
    AADHAR_CHAR:'Minimum 12 char required',
    ESI_CHAR:'Minimum 17 char required',
    PAN_CHAR:'Minimum 10 char required',
    ACCOUNT_CHAR:'Minimum 9 char required'

  },
  success: {
    LEAVE_APPLIED: "Leave applied",
    LOGIN_SUCCESS: "Login Successfull",
    REGISTER_SUCCESS: "Register Successfull",
    LOGOUT_SUCCESS: "User logout successfully",
    UPLOAD_SUCCESS: "File Uploaded successfully",
    GENERATE_SALARY_PASSWORD_SUCCESS: "Salary Password generated successfully",
    CHANGE_PASSWORD_SUCCESS: "Password Changed successfully",
    UPDATE_ACCOUNT_DETAILS_SUCCESS: "Password Changed successfully",
  },
  others: {
    EMAIL_POSTFIX: "@thoughtwin.com",
  },
};
